### ISSUE TITLE
Using HAML unescape syntax gets reformatted

### ISSUE THREAD

**Issue by Petercopter** [ruby-syntax-tree/syntax_tree-haml#29]
https://haml.info/docs/yardoc/file.REFERENCE.html#unescaping_html
```
!= variable
```
gets reformatted into
```
= variable
```
The workaround I'm using right now is
```
variable.html_safe
```

**Comment by kddnewton** [comment]
Oh man, sorry I already fixed this on `main` but forgot to release. I'll publish it soon.

**Comment by Petercopter** [comment]
❤️ 👍
