### ISSUE TITLE
Dependabot merges PRs that do not pass CI

### ISSUE THREAD

**Issue by raxod502** [ruby-syntax-tree/syntax_tree-haml#33]
Looks like the CI errors noted in https://github.com/ruby-syntax-tree/syntax_tree-haml/pull/32 were introduced by https://github.com/ruby-syntax-tree/syntax_tree-haml/pull/31 being auto-merged by https://github.com/ruby-syntax-tree/syntax_tree-haml/blob/8dac2207ae3d24143b735ccfe23d8d0974c74fb6/.github/workflows/main.yml#L28-L41 despite some checks not passing:

![image](https://user-images.githubusercontent.com/6559064/191863239-07d118d4-5ee9-442a-9cef-a449184e9ae3.png)

For some reason the same CI was run twice, but once as a no-op (which passed) and once with the actual tests (which failed). I think the GitHub Actions configuration needs to be updated somehow to prevent that.

**Comment by raxod502** [comment]
Looks like this is (partially) because `pull_request_target` is the wrong trigger to use. Per [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target), it fully ignores the head of the PR and only runs against the base branch, so, of course will pass despite bad code in PR.

I think what we want is a trigger (or action) that will run against a synthesized merge commit instead.

**Comment by kddnewton** [comment]
Ugh... I kind of knew this might be wrong and didn't know how to fix it. Thanks for catching, I'll see what I can find. If you know how to fix this I would appreciate the help as well!

**Comment by raxod502** [comment]
Fixed in https://github.com/ruby-syntax-tree/syntax_tree-haml/pull/38.
