### ISSUE TITLE
Incorrect Formatting for Multiline Attributes

### ISSUE THREAD

**Issue by Petercopter** [ruby-syntax-tree/syntax_tree-haml#35]
Given this code:
```
%ul.nav.nav-tabs.mb-4
  %li.nav-item
    %button.nav-link.active{data: { bs_toggle: 'tab', bs_target: '#file' }, type: 'button' }
      File
  %li.nav-item
    %button.nav-link{ data: { bs_toggle: 'tab', bs_target: '#video' }, type: 'button' }
      Video
```
The first time I save (in VSCode, format on save) I get this, which is expected:
```
%ul.nav.nav-tabs.mb-4
  %li.nav-item
    %button.nav-link.active{
      data: { bs_toggle: 'tab', bs_target: '#file' },
      type: 'button'
    }
      File
  %li.nav-item
    %button.nav-link{
      data: { bs_toggle: 'tab', bs_target: '#video' },
      type: 'button'
    }
      Video
```
But I save again, and it turns into this, which is unexpected:
```
%ul.nav.nav-tabs.mb-4
  %li.nav-item
    %button.nav-link.active{
data: { bs_toggle: 'tab', bs_target: '#file' },
type: 'button'
}
      File
  %li.nav-item
    %button.nav-link{
data: { bs_toggle: 'tab', bs_target: '#video' },
type: 'button'
}
      Video
```
So it appears the syntax_tree formatting is incorrect and not idempotent (vocabulary word!) in this case.

**Comment by kddnewton** [comment]
Thank you! This is indeed a bug. I'll see what I can do.

**Comment by ledermann** [comment]
As a happy user of Prettier for Ruby, I also ran into this bug. I hope it can be fixed.

**Comment by kddnewton** [comment]
> As a happy user of Prettier for Ruby, I also ran into this bug while migration from Slim to Haml. I hope it can be fixed.
> 
> 

@ledermann I'd be happy to accept any pull requests if you want to put one together.

**Comment by kddnewton** [comment]
Now fixed on `main`
