### ISSUE TITLE
Silence Ruby 2.7 Pattern Matching Warning

### ISSUE THREAD

**Issue by nachiket87** [ruby-syntax-tree/syntax_tree-haml#58]
There is a deprecation warning emitted when using Ruby 2.7

```ruby/gems/2.7.0/gems/syntax_tree-haml-2.0.0/lib/syntax_tree/haml/format.rb:437: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!```

Please could this be silenced in the gem?

**Comment by kddnewton** [comment]
Sure yeah, I just removed the internal pattern matching

**Comment by nachiket87** [comment]
Hey! Thanks for fixing so fast! I would've loved to make the PR though 😀

**Comment by kddnewton** [comment]
Whoops! Next time
