### ISSUE TITLE
Keep blank lines in child nodes, too

### ISSUE THREAD

**Issue by ledermann** [ruby-syntax-tree/syntax_tree-haml#77]
Follow up of #63: The formatter of `v4.0.1` keeps blank lines (thanks for this!), but only if they are all root nodes. It does **not** work for child nodes.

This...

```haml
%div
  %p First paragraph

  %p Second paragraph
```

...is formatted as...

```haml
%div
  %p First paragraph
  %p Second paragraph
```

**Comment by kddnewton** [comment]
Ahh shoot yeah I'll fix that too.
