### ISSUE TITLE
Quotes and `=` are removed from interpolated string content

### ISSUE THREAD

**Issue by LaurelOlson** [ruby-syntax-tree/syntax_tree-haml#78]
The quotes and `=` are removed around the following interpolated string on format:

`%span= "- #{foo}"`

becomes

`%span - #{foo}`

This causes invalid syntax and the prettier-ruby plugin then stalls and fails to complete file formatting.

This is using the latest version (4.0.1)

It works if the content is placed on a newline:

```
%span
  = "- #{foo}"
```

**Comment by kddnewton** [comment]
This is by design, taking advantage of their interpolation. See https://haml.info/docs/yardoc/file.REFERENCE.html#ruby-interpolation-. Is it still hanging for you or was that an inline comment like the other issue?

Also thank you very much for the issue reports! I really appreciate the help.

**Comment by LaurelOlson** [comment]
Ah OK thank you!

**Comment by LaurelOlson** [comment]
Inline comment no longer hangs - fixed after updating `prettier_print` as suggested
