### ISSUE TITLE
Issue formatting inline comments

### ISSUE THREAD

**Issue by LaurelOlson** [ruby-syntax-tree/syntax_tree-haml#79]
Comments on the same line as the haml cause the formatter to stall/hang

`%span= foobar # some comment`

Comments on their own line are OK:

```
-# some comment
%span = foobar
```

**Comment by kddnewton** [comment]
Sorry about that! It was an issue in the pretty-printing library causing it to hang forever. If you update `prettier_print` in your bundle to `1.2.1` this should be fixed now.
