### ISSUE TITLE
Unwanted line after HAML filter

### ISSUE THREAD

**Issue by ledermann** [ruby-syntax-tree/syntax_tree-haml#81]
When using [HAML filters](https://haml.info/docs/yardoc/file.REFERENCE.html#filters), the formatter of `v4.0.2` inserts an unwanted blank line.

This ...

```haml
%html
  %head
    :javascript
      console.log('This is inline script');
  %body
    = yield
```

... is formatted as ...

```haml
%html
  %head
    :javascript
      console.log('This is inline script');

  %body
    = yield
```

... is formatted as ...

```haml
%html
  %head
    :javascript
      console.log('This is inline script');


  %body
    = yield
```

... and so on. Note the added line(s) before `%body`.
Each time (e.g. by saving in VSCode) the formatter adds another blank line.

**Comment by kddnewton** [comment]
Thanks for your patience @ledermann, I'll release this in a new patch release momentarily.

**Comment by ledermann** [comment]
Works fine, thanks!
