### ISSUE TITLE
Doesn't respect print-width?

### ISSUE THREAD

**Issue by SimonBrazell** [ruby-syntax-tree/syntax_tree-haml#86]
Hello, trying to get this set up with an existing project, using vscode and prettier + ruby plugin. Most things appear to be working fine except for `printWidth` on HAML files, I can't get the formatter to respect the `printWidth` setting I have in the `.prettierrc.json` file. The HAML parser will turn perfectly valid HAML which is breaking ruby method calls at the comma over multiple lines into one very long line. Is this expected behaviour or am I doing something wrong?

**Comment by SimonBrazell** [comment]
I tried running this from the CLI and got the same results - 
`stree format --print-width=120 --plugins=haml template.haml`

**Comment by kddnewton** [comment]
This is unfortunately by design. HAML can't be split into multiple lines in the same way as Ruby, it's only allowed to have one level of indentation. Because of this we have #4 open.
